package com.example.se.qlsv.dto;

import java.util.Date;

import com.example.se.qlsv.enumric.LessionDay;
import com.example.se.qlsv.enumric.LessionTime;
import com.example.se.qlsv.enumric.LessionType;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class TimeTableDTO {
	private LessionTime endLessionTime;
	private LessionType lessionType;
	private String note;
	private String room;
	private LessionTime startLessionTime;
	private LessionDay lessionDay;
	private Date lessionDate;
	private long sectionClassGroupId;
	private boolean isAutoGenerated;
}
